
version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/user_api
    env_file: .env
    ports:
      - "8000:8000"
#    depends_on:
#      - mongo
#    environment:
#      - MONGO_URI=mongodb+srv://prayansh:projects123@cluster0.ocoebnx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#
#  mongo:
#    image: mongo:4.4
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: prayansh
#      MONGO_INITDB_ROOT_PASSWORD: projects123
#    volumes:
#      - mongo_data:/data/db
#    networks:
#      - backend
#
#  volumes:
#    mongo_data:
#      driver: local


